# Generated by Django 4.2.19 on 2025-02-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVStation',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
