# Generated by Django 4.2.19 on 2025-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_evstation_delete_sensordata_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('available_slots', models.IntegerField(default=0)),
            ],
        ),
    ]
