# Generated by Django 4.2.19 on 2025-02-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evstation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evstation',
            old_name='available_slots',
            new_name='slots',
        ),
        migrations.AlterField(
            model_name='evstation',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
