# Generated by Django 4.2.19 on 2025-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_available_slots_evstation_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_percentage', models.IntegerField(default=100)),
                ('battery_temperature', models.FloatField(default=30.0)),
                ('cng_pressure', models.FloatField(default=10.0)),
                ('cng_temperature', models.FloatField(default=40.0)),
                ('gas_leak_detected', models.BooleanField(default=False)),
            ],
        ),
    ]
